#! /bin/sh
echo "** preinst script for mawk: $*"

set -e

PRI=10
ALT=mawk
PKG=mawk-base

BINDIR=/usr/bin
MANDIR=/usr/share/man/man1

if [ ! -f /usr/bin/mawk-base ]
then
	mv -fv $BINDIR/$ALT      $BINDIR/$PKG 
	mv -fv $MANDIR/$ALT.1.gz $MANDIR/$PKG.1.gz
fi

	update-alternatives \
		--install \
			$BINDIR/$ALT $ALT \
			$BINDIR/$PKG $PRI \
		--slave $MANDIR/$ALT.1.gz $ALT.1.gz \
			$MANDIR/$PKG.1.gz


#DEBHELPER#

exit 0
